force-app/main/default/objects/Orders__c/Orders__c.object-meta.xml
<CustomObject>
    <label>Orders</label>
    <nameField>
        <displayFormat>FK-{0000}</displayFormat>
        <label>Orders Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orders__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>ProductL</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products1s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Clothing</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Groceries</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductOrderLink__c/ProductOrderLink__c.object-meta.xml
<CustomObject>
    <label>ProductOrderLink</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Productorder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductOrderLink</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductOrderLink__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Orders__c</referenceTo>
    <relationshipLabel>ProductOrderLink</relationshipLabel>
    <relationshipName>ProductOrderLink</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductOrderLink__c/fields/Product1__c.field-meta.xml
<CustomField>
    <fullName>Product1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product1</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>ProductOrderLink</relationshipLabel>
    <relationshipName>ProductOrderLink</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductSelectorController.cls
public with sharing class ProductSelectorController {
    
    @AuraEnabled(cacheable=true)
    public static List<Product__c> searchProducts(String searchKey) {
        return [
            SELECT Id, Name, Image_Url__c 
            FROM Product__c 
            WHERE Name LIKE :('%' + searchKey + '%') 
            LIMIT 100
        ];				
    }

    @AuraEnabled
    public static void createOrderLinks(Id orderId, List<Id> productIds) {
        List<ProductOrderLink__c> links = new List<ProductOrderLink__c>();
        for (Id productId : productIds) {
            System.debug('orders : '+orderId+'  productId : '+productId);
            links.add(new ProductOrderLink__c( Orders__c = orderId, Product1__c = productId ));
        }
        insert links;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<product__c> fetchRelatedProduct(Id orderId)
    {
        List<ProductOrderLink__c> ProductOrder = [SELECT Id, Product1__r.Name, Product1__r.Id, Product1__r.Category__c FROM ProductOrderLink__c WHERE Orders__c=:orderId]; 
    	List<Product__c> products = New List<Product__c>();
        for(ProductOrderLink__c POL : ProductOrder)
        {
            products.add(POL.product1__r);
        }
        return products;
    }
    
    @AuraEnabled(cacheable=true)
    public static allRecordsWrapper fetchAllRecordsRelatedToEmail (string email)
    {
        
        //checking if email is not entered
        System.debug('Email :'+email);
        If(String.isBlank(email))
        {
            return null;
        }
        
        //Fetching Contact records and putting in Map.
        List<Contact> conList = [SELECT Id, Name, Email FROM Contact WHERE Email=:email LIMIT 1];
        system.debug('conList : '+conList);
        If(conList.size()==0){
            return null;
        }
   
        
        //Fetching Orders__c records
        List<Orders__c> orderList = [SELECT Id, Name, Contact__c FROM Orders__c WHERE Contact__c=:conList[0].Id];
     	system.debug('orderList : '+orderList);
            
        //Fetching Case records
        List<Case> caseList = [SELECT CaseNumber, Status, ContactId FROM Case WHERE ContactId=:conList[0].Id];
        system.debug('caseList : '+caseList);
        
        
        allRecordsWrapper Wrapper = new allRecordsWrapper();
        Wrapper.contact = conList;
        Wrapper.orders = orderList;
        Wrapper.cases = caseList;
        return Wrapper;
        
    }
    
    //Wrapper Class for "fetchAllRecordsRelatedToEmail"method
    public class allRecordsWrapper{
        @AuraEnabled Public List<Contact> contact;
        @AuraEnabled Public List<Orders__c> orders;
        @AuraEnabled Public List<case> cases;
    }
    	
}