force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cart</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <label>Cart</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cart</relationshipLabel>
    <relationshipName>Cart</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Cart</relationshipLabel>
    <relationshipName>Cart</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>ProductL</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products1s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/D_SOQL_statement.cls
public class D_SOQL_statement
{
    public void demoSOQL()
    {
        List<Account> accList = new List<Account>();
        String AccName = 'Tech School';
        Integer c,d;
        c=[SELECT count() FROM Account WHERE Name =: AccName];
        d=[SELECT count() FROM Account WHERE Name = 'Tech School'];
        System.debug('c='+c+' d='+d);
     }
    
    Public void QueryChildFromParent()
    {
        //Querying Child record from parent record.
        List<Account> accList = new List<Account>();
        accList=[SELECT Id, Name, (SELECT Id, Name FROM contacts) FROM Account WHERE Name='TestAssignmentTrigger2'];
        System.debug('accList => '+accList);
        
        If(!accList.isEmpty())
        {
            for(Account acc : accList)
            {
                System.debug('Acc Contacts => '+acc.contacts);
            }
        }
    }
    
    
    public void QueryParentFromChild()
    {
        List<Cart__c> cartList = new List<Cart__c>();
        cartList=[SELECT Id, Name, product__r.Name,  Product__r.price__c FROM Cart__c];
        System.debug('Cart list => '+cartlist);
        //cartId, cartName and ProductId will be printed.
        
        for(Cart__c car: CartList)
        {
            System.debug(car.Product__r.Name+ ' | '+car.Product__r.price__c);
        }
    }
    
    
    public void InsertRelatedRecords()
    {
        Account acc = new Account(Name='SOQL Test', Phone ='1234567');
        insert acc;
        //after insertion on account account id will be automatically stored in acc.
        //which we are going to use in insertion of related field(contact)
        contact con =  new contact (AccountId = acc.Id,FirstName='Khush', LastName='Rawtiya', Phone='654321');
        insert con;
    }
    

    
    Public void UpdateRelatedRecords()
    {
        contact con =[SELECT Id, Name, Phone, Account.Phone, Account.Name FROM contact WHERE AccountId !=Null AND Account.Name='Tech School3'];
        System.debug(con);
        
        con.Phone = '111111';
        con.Account.Phone = '2222222';
        update con;
        update con.account;
        
    }
}