force-app/main/default/objects/total_oppo_amount__c/total_oppo_amount__c.object-meta.xml
<CustomObject>
    <label>total oppo amount</label>
    <nameField>
        <label>total oppo amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>total oppo amount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/total_oppo_amount__c/fields/Oppo_owner__c.field-meta.xml
<CustomField>
    <fullName>Oppo_owner__c</fullName>
    <label>Oppo owner</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/total_oppo_amount__c/fields/total_amount__c.field-meta.xml
<CustomField>
    <fullName>total_amount__c</fullName>
    <label>total amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Oppo_deal_amount.cls
public class Oppo_deal_amount 
{
    public static void totalAmount()
    {
        List<AggregateResult>aggresult = [select OwnerId, SUM(Amount) totalAmount FROM Opportunity GROUP BY OwnerId];
        
        List<total_oppo_amount__c> record = new List<total_oppo_amount__c>();
        
        for(AggregateResult result : aggresult)
        {
            Id OwnerId=(Id)result.get('OwnerId');
            Decimal totalAmount = (Decimal)result.get('totalAmount');
            
            total_oppo_amount__c customRecord = new total_oppo_amount__c(
            Oppo_owner__c= OwnerId, total_amount__c=totalAmount);
            
            record.add(customRecord);
		}
        
        if(!record.isEmpty()){
            insert record;
        }
    }
}